version: '3.8'

services:
  watchtower:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: watchtower
    restart: always
    ports:
      - "3972:3972"
    volumes:
      - ../watchtower-backend/data:/app/data
      - ../watchtower-backend/configs/.env:/app/configs/.env
      - ../watchtower-backend/configs/config.yaml:/app/configs/config.yaml
    environment:
      - TZ=Asia/Shanghai
    cap_add:
      - NET_RAW
      - NET_ADMIN
